### PR TITLE
Filesystem visibility option

### PR DESCRIPTION
**Pull request by jorisvaesen**
Option to set file either `public` or `private`.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Needs tests.

**Comment by jorisvaesen** [comment]
I know, but phpunit isn't working in my Ubuntu VM for the moment.

**Comment by jorisvaesen** [comment]
Travis doesn't get triggered?

**Comment by ypnos-web** [comment]
I like the idea to explicitely expose this parameter, just a note that setting this is already possible via:
`        'filesystem' => ['options' => ['visibility' => null]]`

**Comment by josegonzalez** [comment]
Oh actually thats probably the better change, to just show how to do that in the docs @ypnos-web .

**Comment by jorisvaesen** [comment]
Wow, missed that option completely.
Is indeed the better change.

**Pull request closed without merging**
