### PR TITLE
update to cake3.6 deprecation changes

### PR DESCRIPTION
**Pull request by Graziel**

### CODE REVIEW

**Comment by raul338** [comment]
This should be merged with #485

**Comment by Graziel** [comment]
woops sorry didnt saw there was already some pr to 3.6, at least i got to remember how to do those

**Comment by raul338** [comment]
May I ask why the changes in src/Database/Type/FileType.php ? I didn't saw any deprecation warnings while using it.

**Comment by Graziel** [comment]
its calling

```
/**
     * {@inheritDoc}
     */
    public function toDatabase($value, Driver $driver)
    {
        return $this->_basicTypeCast($value);
    }
```
and 
`_basicTypeCast($value);` is `deprecated 3.1 All types should now be a specific class`

**Pull request closed without merging**
