### PR TITLE
remove optional parameter value

### LINKED ISSUE #581: Deprecated
Hello.
I am using PHP version 8.1 and CakePHP 4.
I get the following message when I use the plugin: "**Deprecated**: Optional parameter $data declared before required parameter $settings is implicitly treated as a required parameter in /var/www/html/ads4/vendor/josegonzalez/cakephp-upload/src/ Model/Behavior/UploadBehavior.php on line 210".
I have updated the version of the plugin with Composer and the message continues to appear.
I've checked the code for the current Main version and it does indeed have an optional second parameter in the "getWriter" function.
I don't know how to work with GitHub, so I'm hesitant to upload the fix.
Thanks a lot

### PR DESCRIPTION
**Pull request by saeideng**
I changed also the interface
not sure if it is BC
Closes #581

### CODE REVIEW

**Comment by davidyell** [comment]
Seems sensible, although with it typed as `?UploadedFileInterface` will the default type be `null` ?

**Comment by saeideng** [comment]
> Seems sensible

no default value , because you have to pass all parameters 
you can not have default value ( no passing ) when next parameters are required

**Comment by saeideng** [comment]
it means you can not have 
```php
->getWriter($entity);
```

**Comment by saeideng** [comment]
test with named Argument: 
```php
class A
{
    public string $first;
    public ?string $nullableString;
    public int $third;
    public function __construct(
        string $first,
        ?string $nullableString = null,
        int $third,
    ) {
       
        $this->first = $first;
        $this->nullableString = $nullableString;
        $this->third = $third;
    }
    public function dump(){
        var_dump($this->first);
        var_dump($this->nullableString);
        var_dump($this->third);
    }
}
$data = new A(
    'a string',
    third: 20,
    
);
$data->dump();
```

current implementation only works in php 8.0 when you use named Argument 
```php
//result php 8.0
string(8) "a string"
NULL
int(20)
```
```php
//result php 8.1
Deprecated: Optional parameter $nullableString declared before required parameter $third is implicitly treated as a required parameter
Fatal error: Uncaught ArgumentCountError: A::__construct(): Argument #2 ($nullableString) not passed
```

**Review by davidyell — APPROVED** [review]

**Comment by saeideng** [comment]
extending class test:

```php
class A
{
    public  $p;
    public function func(
        int $p = null
    ){
        $this->p = $p;
    }
}
class B extends A
{
    public  $p;
    public function func(
        ?int $p = null
    ) {
        $this->p = $p;
    }
    public function dump(){
        var_dump($this->p);
    }
}
$data = new B();
$data->func(50);
$data->dump();
```

php 7.1+ 
```
int(50)
```

another test:
implement interface
```php
interface AInterface
{
    public function __construct(
        string $p = null
    );
}
class A implements AInterface
{
    public $p;
    public function __construct(
        ?string $p = null
    ) {
        $this->p = $p;
    }
    public function dump(){
        var_dump($this->p);
    }
}
$data = new A(
    'a string'
);
$data->dump();
```
php 7.1+
```
string(8) "a string"
```

**Pull request merged**
