### PR TITLE
Prepare for CakePHP 3.6

### PR DESCRIPTION
**Pull request by raul338**
Update code to remove deprecations.

Maybe I should drop PHP 5.5 ?

### CODE REVIEW

**Comment by raul338** [comment]
This should be ready to merge

**Comment by raul338** [comment]
Done. What else should be done ?

**Comment by josegonzalez** [comment]
Seems reasonable. Can you smoke-test this in an app and verify everything works as you expect?

**Comment by raul338** [comment]
As of now, Upload works. The code I used is based of the examples. KeepFilesOnDelete set false also works

```php
$this->addBehavior('Josegonzalez/Upload.Upload', [
    'foto' => [
        'path' => 'webroot{DS}img{DS}uploads{DS}tickets{DS}{field-value:ticket_id}{DS}',
        'nameCallback' => function ($data, $settings) {
            return time() . '_' . $data['name'];
        },
    ],
]);
// ....
$validator->setProvider('upload', UploadValidation::class);
$validator->add('foto', 'fileFileUpload', [
    'rule' => 'isFileUpload',
    'message' => 'Debe cargar una foto',
    'provider' => 'upload',
    'on' => 'create',
]);
```

**Comment by bmeclazcke** [comment]
Hey all!

Any ETA on when is this going to be released?

Thanks!

**Comment by josegonzalez** [comment]
Now seems fine.

**Comment by josegonzalez** [comment]
Released 4.0.0.

**Comment by Spriz** [comment]
FYI:

It says in the release that Cake 3.6 is required ("This change requires at least CakePHP 3.6, and should support the upcoming 4.x release.")

But it only seems to require Cake 3.4 in the `composer.json`

**Pull request merged**
